import { Salon, Category, Testimonial, Service, BookingStep } from './types'

export const SALONS: Salon[] = [
  {
    id: '1',
    name: 'Lavelle Beauty Mumbai',
    area: 'Bandra West',
    city: 'Mumbai',
    rating: 4.9,
    reviewCount: 342,
    priceLevel: 3,
    services: ['Bridal', 'Makeup', 'Hair'],
    image: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=800&q=80',
    badge: 'Most Booked',
    description: 'Premium luxury salon specializing in bridal makeup and hair styling. Known for exceptional service and attention to detail.',
    highlights: ['AC', 'Parking', 'WiFi', 'Card Accepted'],
    hours: { open: '10:00', close: '20:00' },
    phone: '+91 9876543210',
    address: 'Linking Road, Bandra West, Mumbai 400050',
    lat: 19.0544,
    lng: 72.8229,
  },
  {
    id: '2',
    name: 'Aurora Beauty Lounge',
    area: 'Juhu',
    city: 'Mumbai',
    rating: 4.8,
    reviewCount: 218,
    priceLevel: 4,
    services: ['Luxury Spa', 'Facial', 'Nails'],
    image: 'https://images.unsplash.com/photo-1600948836101-f9ff5fbc291c?w=800&q=80',
    badge: 'New',
    description: 'Modern beauty lounge offering luxury spa treatments and premium nail services in a serene environment.',
    highlights: ['AC', 'Valet Parking', 'WiFi', 'Card Accepted', 'Refreshments'],
    hours: { open: '09:00', close: '21:00' },
    phone: '+91 9876543211',
    address: 'Juhu Tara Road, Juhu, Mumbai 400049',
    lat: 19.1077,
    lng: 72.8263,
  },
  {
    id: '3',
    name: 'Blush Studio Mumbai',
    area: 'Andheri West',
    city: 'Mumbai',
    rating: 4.7,
    reviewCount: 189,
    priceLevel: 2,
    services: ['Hair', 'Nails', 'Threading'],
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&q=80',
    badge: 'Best Value',
    description: 'Affordable yet professional salon offering quality hair and nail services with quick turnaround times.',
    highlights: ['AC', 'Parking', 'Card Accepted'],
    hours: { open: '10:00', close: '20:00' },
    phone: '+91 9876543212',
    address: 'SV Road, Andheri West, Mumbai 400058',
    lat: 19.1197,
    lng: 72.8466,
  },
  {
    id: '4',
    name: 'The Glow Room',
    area: 'Worli',
    city: 'Mumbai',
    rating: 4.9,
    reviewCount: 421,
    priceLevel: 4,
    services: ['Bridal', 'Makeup', 'Hair Spa'],
    image: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&q=80',
    badge: 'Top Rated',
    description: 'Exclusive salon offering premium bridal packages and therapeutic hair spa treatments.',
    highlights: ['AC', 'Parking', 'WiFi', 'Card Accepted', 'Private Rooms'],
    hours: { open: '09:30', close: '20:30' },
    phone: '+91 9876543213',
    address: 'Worli Sea Face, Worli, Mumbai 400018',
    lat: 19.0176,
    lng: 72.8212,
  },
  {
    id: '5',
    name: 'Velvet Touch Salon',
    area: 'Colaba',
    city: 'Mumbai',
    rating: 4.6,
    reviewCount: 156,
    priceLevel: 2,
    services: ['Hair', 'Facial', 'Waxing'],
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800&q=80',
    description: 'Classic salon with experienced stylists offering traditional and modern hair and skincare services.',
    highlights: ['AC', 'Card Accepted'],
    hours: { open: '10:00', close: '19:30' },
    phone: '+91 9876543214',
    address: 'Colaba Causeway, Colaba, Mumbai 400005',
    lat: 18.9157,
    lng: 72.8259,
  },
  {
    id: '6',
    name: 'Radiance Beauty Bar',
    area: 'Powai',
    city: 'Mumbai',
    rating: 4.8,
    reviewCount: 203,
    priceLevel: 3,
    services: ['Nails', 'Makeup', 'Lashes'],
    image: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&q=80',
    badge: 'Trending',
    description: 'Trendy beauty bar specializing in nail art, makeup, and eyelash extensions for modern clients.',
    highlights: ['AC', 'WiFi', 'Card Accepted', 'Online Booking'],
    hours: { open: '10:30', close: '21:00' },
    phone: '+91 9876543215',
    address: 'Hiranandani Gardens, Powai, Mumbai 400076',
    lat: 19.1176,
    lng: 72.9060,
  },
]

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Bridal Makeup',
    icon: 'sparkles',
    salonCount: 42,
    color: 'from-rose-gold to-blush',
  },
  {
    id: '2',
    name: 'Hair Styling',
    icon: 'scissors',
    salonCount: 68,
    color: 'from-espresso to-rose-gold',
  },
  {
    id: '3',
    name: 'Nail Art',
    icon: 'paintbrush',
    salonCount: 53,
    color: 'from-blush to-rose-gold',
  },
  {
    id: '4',
    name: 'Facial & Skin',
    icon: 'leaf',
    salonCount: 47,
    color: 'from-rose-gold to-espresso',
  },
  {
    id: '5',
    name: 'Hair Spa',
    icon: 'droplets',
    salonCount: 39,
    color: 'from-espresso to-blush',
  },
  {
    id: '6',
    name: 'Makeup Studio',
    icon: 'star',
    salonCount: 61,
    color: 'from-blush to-espresso',
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    location: 'Bandra',
    rating: 5,
    text: 'Booked my bridal makeup through GlowCity and it was absolutely perfect. The AI recommendation was spot on!',
    avatarInitials: 'PS',
  },
  {
    id: '2',
    name: 'Ananya Mehta',
    location: 'Juhu',
    rating: 5,
    text: 'Found my go-to nail studio in 2 minutes. The search filters are amazing.',
    avatarInitials: 'AM',
  },
  {
    id: '3',
    name: 'Riya Kapoor',
    location: 'Andheri',
    rating: 4,
    text: 'Best salon discovery app in Mumbai. My blowout was everything!',
    avatarInitials: 'RK',
  },
]

export const SERVICES: Service[] = [
  {
    id: '1',
    name: 'Bridal Makeup Package',
    category: 'Makeup',
    duration: '3 hours',
    price: 15000,
    description: 'Complete bridal makeup with trial session',
  },
  {
    id: '2',
    name: 'Haircut & Styling',
    category: 'Hair',
    duration: '1 hour',
    price: 1200,
    description: 'Professional haircut and styling',
  },
  {
    id: '3',
    name: 'Manicure & Nail Art',
    category: 'Nails',
    duration: '45 mins',
    price: 800,
    description: 'Basic manicure with nail art',
  },
  {
    id: '4',
    name: 'Gold Facial',
    category: 'Facial',
    duration: '1.5 hours',
    price: 2500,
    description: 'Luxury gold facial treatment',
  },
  {
    id: '5',
    name: 'Hair Spa Treatment',
    category: 'Hair Spa',
    duration: '2 hours',
    price: 1800,
    description: 'Complete hair spa with massage',
  },
  {
    id: '6',
    name: 'Party Makeup',
    category: 'Makeup',
    duration: '1.5 hours',
    price: 3000,
    description: 'Evening party makeup with HD finish',
  },
]

export const BOOKING_STEPS: BookingStep[] = [
  {
    id: '1',
    title: 'Search',
    description: 'Find salons by area or service in Mumbai',
    number: 1,
  },
  {
    id: '2',
    title: 'Choose',
    description: 'Pick your stylist, time and service',
    number: 2,
  },
  {
    id: '3',
    title: 'Glow',
    description: 'Walk in and experience luxury',
    number: 3,
  },
]

export const AREAS = [
  'Bandra', 'Juhu', 'Andheri', 'Colaba', 'Worli', 'Powai', 'Malad', 'Borivali'
]

export const SERVICE_TYPES = [
  'Hair', 'Makeup', 'Nails', 'Facial', 'Bridal', 'Waxing', 'Spa'
]